//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModelFirstApproachDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public int OrderInfoID { get; set; }
        public string Description { get; set; }
        public System.DateTime Time { get; set; }
        public int OrderUserID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
